version: '3'
services:
  ap:
    build: ./docker/ap
    container_name: "ap"
    volumes:
      - ./server/ap/src:/var/www
    links:
      - db
    depends_on:
      - db
    ports:
      - 9000:9000
      - 8080:8000
  db:
    image: mysql:8.0.20
    container_name: "db"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hogehoge
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hoge
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4
    command: mysqld --collation-server=utf8mb4_unicode_ci
    command: mysqld --default_authentication_plugin=mysql_native_password
